name: model-training
on: [push]
jobs:
	run:
		runs-on: [ubuntu-latest]
		steps:
			- uses: actions/checkout@v2
			- uses: actions/setup-python@v2
			- uses: iterative/setup-cml@v1
			- name: train model
				run: |
					pip install -r requirements.txt

			- name: run tests
					 python -m unittest discover tests
				run: |
					# Post reports as comments in GitHub PRs
					# LSTM
					cd img/
					echo "## Model Training Completed" > report.md
					echo "### Model training history" >> report.md